/** @type {import('tailwindcss').Config} */
// Tema portado del Stitch Design System de DocSwarm (Material 3 · "Agro Teal").
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-error": "#ffffff",
        "on-primary-fixed": "#002020",
        "on-tertiary": "#ffffff",
        "primary-fixed-dim": "#76d6d5",
        "surface-dim": "#d3daea",
        "surface-container-low": "#f0f3ff",
        "on-surface": "#151c27",
        "on-secondary": "#ffffff",
        "primary-fixed": "#93f2f2",
        "on-secondary-container": "#5c6274",
        "on-secondary-fixed-variant": "#404758",
        "surface-container-highest": "#dce2f3",
        "secondary-container": "#d9dff5",
        "secondary-fixed": "#dce2f7",
        surface: "#f9f9ff",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#191c1e",
        "tertiary-fixed-dim": "#c5c6c8",
        "outline-variant": "#bdc9c8",
        primary: "#006565",
        "surface-container-high": "#e2e8f8",
        "inverse-primary": "#76d6d5",
        "secondary-fixed-dim": "#c0c6db",
        "surface-bright": "#f9f9ff",
        "on-background": "#151c27",
        "surface-tint": "#006a6a",
        "surface-variant": "#dce2f3",
        "surface-container": "#e7eefe",
        secondary: "#575e70",
        tertiary: "#585b5c",
        "on-tertiary-fixed-variant": "#444749",
        "primary-container": "#008080",
        "on-primary": "#ffffff",
        background: "#f9f9ff",
        "on-surface-variant": "#3e4949",
        "on-secondary-fixed": "#141b2b",
        "inverse-on-surface": "#ebf1ff",
        "on-tertiary-container": "#f9fafc",
        "on-error-container": "#93000a",
        "tertiary-container": "#717375",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004f4f",
        "inverse-surface": "#2a313d",
        outline: "#6e7979",
        "on-primary-container": "#e3fffe",
        "tertiary-fixed": "#e1e2e4",
        // Sistema semáforo (badges/estados)
        "ok-bg": "#E6F4EA",
        "ok-fg": "#137333",
        "warn-bg": "#FFF8E1",
        "warn-fg": "#F57F17",
        "danger-bg": "#FCE8E6",
        "danger-fg": "#C5221F",
        "info-bg": "#E8F0FE",
        "info-fg": "#1A56DB",
        "neutral-bg": "#ECEFF4",
        "neutral-fg": "#4B5563",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
      spacing: {
        gutter: "16px",
        "stack-compact": "8px",
        "stack-relaxed": "24px",
        "container-margin": "24px",
        unit: "4px",
      },
      padding: {
        "table-cell-padding": "12px 16px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "title-sm": ["Inter"],
        "display-lg": ["Inter"],
        "label-caps": ["Inter"],
        "data-mono": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "data-mono": ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
